name: build-macos
on: [push, pull_request]
jobs:

  macos_latest_cmake:
    runs-on: macos-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS CMake without Python
            python: without
          - name: macOS CMake with Python
            python: with
          - name: macOS CMake with SYMBOLSUFFIX
            python: without
            symbolsuffix: '_64'
    steps:
      - name: Clone and check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}} # Branch where changes are implemented.
          repository: ${{github.event.pull_request.head.repo.full_name}} # Repo where changes are implemented.
      - name: Check commit
        run: |
          git log -1
      - name: Install brew dependencies
        run: |
          if [ "${{ matrix.python }}" == "with" ]; then
              # Unlink and re-link to prevent errors when github mac runner images
              # install python outside of brew, for example:
              # https://github.com/orgs/Homebrew/discussions/3895
              # https://github.com/actions/setup-python/issues/577
              # https://github.com/actions/runner-images/issues/6459
              # https://github.com/actions/runner-images/issues/6507
              # https://github.com/actions/runner-images/issues/2322
              brew list -1 | grep python | while read formula; do brew unlink $formula; brew link --overwrite $formula; done
          fi
          brew reinstall gcc # brings gfortran on path
          brew install cmake eigen \
            $([ x"${{ matrix.symbolsuffix }}" == x"_64" ] && echo "openblas64" || echo "open-mpi veclibfort") \
            $([ "${{ matrix.python }}" == "with" ] && echo "boost-python3 python3 numpy" || echo " ")
      - name: Setup environment
        run: |
          if [ "${{ matrix.python }}" == "without" && x"${{ matrix.symbolsuffix }}" != x"_64"]; then
            # use MPI compiler wrappers
            echo "FC=mpif90" >> $GITHUB_ENV
            echo "CC=mpicc" >> $GITHUB_ENV
            echo "CXX=mpic++" >> $GITHUB_ENV
          else
            # use compiler drivers directly
            echo "FC=gfortran" >> $GITHUB_ENV
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi
      - name: Configure
        run: |
          mkdir -p build
          cd build
          export CFLAGS="-Qunused-arguments"
          export CXXFLAGS="-Qunused-arguments"
          declare -a _extra_config
          if [ x"${{ matrix.symbolsuffix }}" == x"_64" ]; then
            export OPENBLAS64_PREFIX="$(brew --prefix openblas64)"
            _extra_config+=("-DBLAS_LIBRARIES=${OPENBLAS64_PREFIX}/lib/libopenblas64_.dylib"
                            "-DLAPACK_LIBRARIES=${OPENBLAS64_PREFIX}/lib/libopenblas64_.dylib"
                            "-DSYMBOLSUFFIX=_64"
                            "-DINTERFACE64=1")
          else
            export VECLIBFORT_PREFIX="$(brew --prefix veclibfort)"
            _extra_config+=("-DBLAS_LIBRARIES=${VECLIBFORT_PREFIX}/lib/libvecLibFort.dylib"
                            "-DLAPACK_LIBRARIES=${VECLIBFORT_PREFIX}/lib/libvecLibFort.dylib"
                            "-DMPI=ON")
          fi
          cmake \
            "${_extra_config[@]}" \
            -DEXAMPLES=ON -DICB=ON -DEIGEN=ON \
            $([ "${{ matrix.python }}" == "with" ] && echo "-DPYTHON3=ON" || echo "") \
            ..
      - name: Build
        run: |
          cd build
          make all
      - name: Run tests
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=1 make test

  macos_latest_autotools:
    runs-on: macos-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS autotools
          - name: macOS autotools with SYMBOLSUFFIX
            symbolsuffix: '_64'
    steps:
      - name: Clone and check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}} # Branch where changes are implemented.
          repository: ${{github.event.pull_request.head.repo.full_name}} # Repo where changes are implemented.
      - name: Check commit
        run: |
          git log -1
      - name: Install brew dependencies
        run: |
          brew reinstall gcc # brings gfortran on path
          brew install autoconf automake libtool pkgconfig eigen \
            $([ x"${{ matrix.symbolsuffix }}" == x"_64" ] && echo "openblas64" || echo "open-mpi veclibfort")
      - name: Configure
        run: |
          ./bootstrap
          declare -a _extra_config
          if [ x"${{ matrix.symbolsuffix }}" == x"_64" ]; then
            export OPENBLAS64_PREFIX="$(brew --prefix openblas64)"
            _extra_config+=("--with-blas=-L${OPENBLAS64_PREFIX}/lib -lopenblas64_"
                            "--with-lapack=-L${OPENBLAS64_PREFIX}/lib -lopenblas64_"
                            "SYMBOLSUFFIX=_64"
                            "INTERFACE64=1")
            # The line length of fixed-length source files might be exceeded
            # after post-processing with the additional suffix.
            # Make gfortran more lenient when it comes to long lines.
            _extra_config+=("FFLAGS=-ffixed-line-length-none")
          else
            export VECLIBFORT_PREFIX="$(brew --prefix veclibfort)"
            _extra_config+=("--with-blas=-L${VECLIBFORT_PREFIX}/lib -lvecLibFort"
                            "--with-lapack=-L${VECLIBFORT_PREFIX}/lib -lvecLibFort"
                            "--enable-mpi")
          fi
          ./configure \
            "${_extra_config[@]}" \
            --enable-icb --enable-eigen
      - name: Build
        run: |
          make all
      - name: Run checks
        run: |
          make check
