name: build-ubuntu
on: [push, pull_request]
jobs:

  ubuntu_latest_cmake:
    runs-on: ubuntu-latest
    name: Ubuntu CMake ${{ matrix.tests }} tests ${{ matrix.install }} install ${{ matrix.python }} Python
    strategy:
      fail-fast: false
      matrix:
        include:
          - tests: with
            install: without
            python: without
          - tests: without
            install: with
            python: without
          - tests: with
            install: without
            python: with
    steps:
      - name: Clone and check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}} # Branch where changes are implemented.
          repository: ${{github.event.pull_request.head.repo.full_name}} # Repo where changes are implemented.
      - name: Check commit
        run: |
          git log -1
      - name: Update OS
        run: sudo apt-get update
      - name: Install apt-get dependencies
        run: sudo apt-get install -y gfortran gcc g++ openmpi-bin libopenmpi-dev libblas-dev liblapack-dev libeigen3-dev cmake
      - name: Install python dependencies
        if: matrix.python == 'with'
        run: sudo apt-get -y install python3-minimal python3-pip python3-numpy
      - name: Build boost-python for python3 (not provided by apt-cache)
        if: matrix.python == 'with'
        run : |
          sudo apt-get -y install wget
          wget https://sourceforge.net/projects/boost/files/boost/1.79.0/boost_1_79_0.tar.gz
          tar -xf boost_1_79_0.tar.gz
          cd boost_1_79_0
          ./bootstrap.sh --with-libraries=python --with-python=/usr/bin/python3 --with-toolset=gcc
          sudo ./b2 toolset=gcc install
          sudo apt-get install locate
          sudo updatedb
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake \
            $([ "${{ matrix.tests }}" == "with" ] && echo "-DEXAMPLES=ON -DMPI=ON -DICB=ON -DEIGEN=ON" || echo "") \
            $([ "${{ matrix.python }}" == "with" ] && echo "-DPYTHON3=ON" || echo "") \
            ..
      - name: Build and install
        if: matrix.install == 'with'
        run: |
          cd build
          bash ./tstCMakeInstall.sh
      - name: Build and install '64-'
        if: matrix.install == 'with'
        run: |
          cd build
          bash ./tstCMakeInstall.sh 64-
      - name: Build and install '-ILP64'
        if: matrix.install == 'with'
        run: |
          cd build
          bash ./tstCMakeInstall.sh   -ILP64
      - name: Build and install '64-ILP64'
        if: matrix.install == 'with'
        run: |
          cd build
          bash ./tstCMakeInstall.sh 64-ILP64
      - name: Build
        if: matrix.tests == 'with'
        run: |
          cd build
          make all
      - name: Run tests
        if: matrix.tests == 'with'
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=1 make test
      - name: Create source package
        if: matrix.tests == 'with'
        run: |
          cd build
          make package_source

  ubuntu_latest_autotools:
    runs-on: ubuntu-latest
    name: Ubuntu autotools ${{ matrix.tests }} tests ${{ matrix.install }} install using ${{ matrix.blas }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - tests: with
            install: without
            blas: BLAS
            configure-flags: --enable-mpi --enable-icb --enable-eigen
          - tests: without
            install: with
            blas: BLAS
            configure-flags:
          - tests: with
            install: without
            blas: MKL
            configure-flags: --enable-icb --with-blas=mkl_gf_ilp64 --with-lapack=mkl_gf_ilp64
    steps:
      - name: Clone and check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}} # Branch where changes are implemented.
          repository: ${{github.event.pull_request.head.repo.full_name}} # Repo where changes are implemented.
      - name: Check commit
        run: |
          git log -1
      - name: Update OS
        run: sudo apt-get update
      - name: Install apt-get dependencies
        run: |
          sudo apt-get install -y \
            gfortran gcc g++ openmpi-bin libopenmpi-dev \
            $([ "${{ matrix.blas }}" != "BLAS" ] || echo "libblas-dev liblapack-dev") \
            libeigen3-dev automake autoconf pkg-config libtool
          if [ "${{ matrix.blas }}" == "MKL" ]; then
            echo "::group::Install Intel MKL (ILP64 BLAS/LAPACK)"
            echo yes | sudo apt-get -y install intel-mkl libmkl-dev
            echo "::endgroup::"
          fi
      - name: Setup environment for MKL
        if: matrix.blas == 'MKL'
        run: |
          echo "FFLAGS=-DMKL_ILP64 -I/usr/include/mkl" >> $GITHUB_ENV
          echo "FCFLAGS=-DMKL_ILP64 -I/usr/include/mkl" >> $GITHUB_ENV
          echo "LIBS=-Wl,--no-as-needed -L/usr/lib/x86_64-linux-gnu -lmkl_sequential -lmkl_core -lpthread -lm -ldl" >> $GITHUB_ENV
          echo "INTERFACE64=1" >> $GITHUB_ENV
      - name: Configure
        run: |
          ./bootstrap
          ./configure ${{ matrix.configure-flags }}
      - name: Build and install
        if: matrix.install == 'with'
        run: |
          bash ./tstAutotoolsInstall.sh
      - name: Build and install '64-'
        if: matrix.install == 'with'
        run: |
          bash ./tstAutotoolsInstall.sh 64-
      - name: Build and install '-ILP64'
        if: matrix.install == 'with'
        run: |
          bash ./tstAutotoolsInstall.sh   -ILP64
      - name: Build and install '64-ILP64'
        if: matrix.install == 'with'
        run: |
          bash ./tstAutotoolsInstall.sh 64-ILP64
      - name: Build
        if: matrix.tests == 'with'
        run: |
          make all
      - name: Run checks
        if: matrix.tests == 'with'
        run: |
          make check
      - name: Run distchecks
        if: matrix.tests == 'with' && matrix.blas != 'MKL'
        run: |
          make distcheck
