name: build-macos
on: [push, pull_request]
jobs:
  macos_latest_cmake:
    runs-on: macos-latest
    steps:
      - name: Clone and check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}} # Branch where changes are implemented.
          repository: ${{github.event.pull_request.head.repo.full_name}} # Repo where changes are implemented.
      - name: Check commit
        run: |
          git log -1
      - name: Install brew dependencies
        run: |
          brew reinstall gcc # brings gfortran on path
          brew install cmake open-mpi eigen veclibfort
      - name: Run job
        run: |
          mkdir -p build
          cd build
          export FC=mpif90 # Uses gfortran.
          export CC=mpicc # Uses clang.
          export CFLAGS="-Qunused-arguments"
          export CXX=mpic++ # Uses clang++.
          export CXXFLAGS="-Qunused-arguments"
          export VECLIBFORT_PREFIX=$(brew --prefix veclibfort)
          cmake \
            -DBLAS_LIBRARIES="${VECLIBFORT_PREFIX}/lib/libvecLibFort.dylib" \
            -DLAPACK_LIBRARIES="${VECLIBFORT_PREFIX}/lib/libvecLibFort.dylib" \
            -DEXAMPLES=ON -DICB=ON -DEIGEN=ON -DMPI=ON ..
          make all
          CTEST_OUTPUT_ON_FAILURE=1 make test
  macos_latest_cmake_python:
    runs-on: macos-latest
    steps:
      - name: Clone and check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}} # Branch where changes are implemented.
          repository: ${{github.event.pull_request.head.repo.full_name}} # Repo where changes are implemented.
      - name: Check commit
        run: |
          git log -1
      - name: Install brew dependencies
        run: |
          # Unlink and re-link to prevent errors when github mac runner images
          # install python outside of brew, for example:
          # https://github.com/orgs/Homebrew/discussions/3895
          # https://github.com/actions/setup-python/issues/577
          # https://github.com/actions/runner-images/issues/6459
          # https://github.com/actions/runner-images/issues/6507
          # https://github.com/actions/runner-images/issues/2322
          brew list -1 | grep python | while read formula; do brew unlink $formula; brew link --overwrite $formula; done
          brew reinstall gcc # brings gfortran on path
          brew install cmake eigen boost-python3 python3 numpy veclibfort
      - name: Run job
        run: |
          mkdir -p build
          cd build
          export FC=gfortran
          export CC=clang
          export CFLAGS="-Qunused-arguments"
          export CXX=clang++
          export CXXFLAGS="-Qunused-arguments"
          export VECLIBFORT_PREFIX=$(brew --prefix veclibfort)
          cmake \
            -DBLAS_LIBRARIES="${VECLIBFORT_PREFIX}/lib/libvecLibFort.dylib" \
            -DLAPACK_LIBRARIES="${VECLIBFORT_PREFIX}/lib/libvecLibFort.dylib" \
            -DEXAMPLES=ON -DICB=ON -DEIGEN=ON -DPYTHON3=ON ..
          make all
          CTEST_OUTPUT_ON_FAILURE=1 make test
  macos_latest_autotools:
    runs-on: macos-latest
    steps:
      - name: Clone and check out repository code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}} # Branch where changes are implemented.
          repository: ${{github.event.pull_request.head.repo.full_name}} # Repo where changes are implemented.
      - name: Check commit
        run: |
          git log -1
      - name: Install brew dependencies
        run: |
          brew reinstall gcc # brings gfortran on path
          brew install autoconf automake libtool pkgconfig open-mpi eigen veclibfort
      - name: Run job
        run: |
          ./bootstrap
          export VECLIBFORT_PREFIX=$(brew --prefix veclibfort)
          BLAS_LIBS="-L${VECLIBFORT_PREFIX}/lib -lvecLibFort" \
          LAPACK_LIBS="-L${VECLIBFORT_PREFIX}/lib -lvecLibFort" \
            ./configure --enable-icb --enable-eigen --enable-mpi
          make all
          make check
